# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title 
auto: true
pygments: true
var:
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  rss_path: /atom.xml

production_url : http://username.github.com # or your custom domain name
title : Jekyll Bootstrap

author :
  name : Name Lastname
  email : blah@email.test
  github : username
  twitter : username
  feedburner : feedname

exclude: [".rbenv-version", "README.md", "Rakefile"]

# Jekyll-Bootstrap configurations
JB :
  
  # All links will be namespaced by BASE_PATH if defined.
  # This is required for hosting GitHub Project Pages.
  # If you are deploying this website for one of your GitHub projects
  # you must set BASE_PATH to the name of your GitHub project.
  #
  BASE_PATH : "/narly"

  # By default, the asset_path is automatically defined relative to BASE_PATH plus the enabled theme.
  # ex: [BASE_PATH]/assets/themes/[THEME-NAME]
  #
  # Override this by defining an absolute path to assets here.
  # ex: 
  #   http://s3.amazonaws.com/yoursite/themes/watermelon
  #   /assets
  #
  ASSET_PATH : false
  
  
  comments :
    engine : disqus
    disqus :
      short_name : jekyllbootstrap
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      apikey : 123
   
        
  analytics :
    engine : google
    google : 
        tracking_id : 'UA-123-12'
    getclicky :
      site_id : 


  sharing :
    engine : false